version : "3"
services:
  backend:
    build: ./backend
    container_name: 'back-turismo'
    command: sh -c 'python app.py'
    ports:
      - '5000:5000'
    volumes:
      - './backend:/backend'
    depends_on:
      - 'db-turismo'

  db-turismo:
    container_name: 'api-turismo'
    image: redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: 'front-turismo'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/frontend'
    depends_on:
      - "backend"
    stdin_open: true
    tty: true
